services:
  ombi:
    image: lscr.io/linuxserver/ombi:${OMBI_VERSION}
    container_name: ombi
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/ombi/config:/config
    ports:
      - ${OMBI_PORT}:3579
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
