version: "3.8"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:${PROWLARR_VERSION}
    container_name: prowlarr
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/prowlarr/config:/config
    ports:
      - ${PROWLARR_PORT}:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
  