services:
  radarr:
    image: lscr.io/linuxserver/radarr:${RADARR_VERSION}
    container_name: radarr
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/radarr/config:/config
      - ./data:/data
    ports:
      - ${RADARR_PORT}:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
