version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    labels:
      - "co.elastic.logs/enabled=true"
    env_file: .env
    volumes:
      - ./appdata/radarr/config:/config
      - ./data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
