filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log
        scan_frequency: 30s
      hints.default_config.enabled: false

output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  ssl.certificate_authorities: ["config/certs/ca/ca.crt"]
  username: 'elastic'
  password: '${ELASTIC_PASSWORD}'

setup:
  # TODO Fix enable dashboard: With this option enabled, container is exited due to the following error "Exiting: error connecting to Kibana: fail to get the Kibana version: fail to parse kibana version (): passed version is not semver:" (Kibana is reachable though)
  dashboards.enabled: false
  ilm.check_exists: false
  kibana:
    host: "http://kibana:5601"
    username: 'kibana_system'
    password: ${KIBANA_PASSWORD}'