version: "3.8"

services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    labels:
      - "co.elastic.logs/enabled=true"
    env_file: .env
    volumes:
      - ./appdata/readarr/config:/config
      - ./data:/data
    ports:
      - 8787:8787
    restart: unless-stopped

