version: "3.8"

services:
  readarr:
    image: lscr.io/linuxserver/readarr:${READARR_VERSION}
    container_name: readarr
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/readarr/config:/config
      - ./data:/data
    ports:
      - ${READARR_PORT}:8787
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

