version: "3.8"

services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:${GLUETUN_VERSION}
    container_name: gluetun
    labels:
      - "co.elastic.logs/enabled=true"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./appdata/gluetun/data:/gluetun
    ports:
      - ${GLUETUN_PORT_HTTP_PROXY}:8888/tcp # HTTP proxy
      - ${GLUETUN_PORT_SHADOWSOCKS}:8388/tcp # Shadowsocks
      - ${GLUETUN_PORT_SHADOWSOCKS}:8388/udp # Shadowsocks
      - ${QBITTORRENT_PORT_WEBI}:${QBITTORRENT_PORT_WEBI} # qbittorrent web interface
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT} # qbittorrent
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/udp # qbittorrent
    restart: unless-stopped
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - FREE_ONLY=${FREE_ONLY}
      - UPDATER_PERIOD=${UPDATER_PERIOD}