version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    labels:
      - "co.elastic.logs/enabled=true"
    env_file: .env
    environment:
      - WEBUI_PORT=8080
    volumes:
      - ./appdata/qbittorrents/config:/config
      - ./data/torrents:/data/torrents
    network_mode: "service:gluetun"
    restart: unless-stopped