services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    depends_on:
      gluetun:
        condition: service_healthy
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/qbittorrents/config:/config
      - ./data/torrents:/data/torrents
    network_mode: "service:gluetun"
    environment:
      - WEBUI_PORT=8080
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped