services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:${LIDARR_VERSION}
    container_name: lidarr
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/lidarr/config:/config
      - ./data:/data
    ports:
      - ${LIDARR_PORT}:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped