version: "3.8"

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    labels:
      - "co.elastic.logs/enabled=true"
    env_file: .env
    volumes:
      - ./appdata/lidarr/config:/config
      - ./data:/data
    ports:
      - 8686:8686
    restart: unless-stopped