version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/sonarr/config:/config
      - ./data:/data
    ports:
      - ${SONARR_PORT}:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped