version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - "co.elastic.logs/enabled=true"
    env_file: .env
    volumes:
      - ./appdata/sonarr/config:/config
      - ./data:/data
    ports:
      - 8989:8989
    restart: unless-stopped