
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    env_file: .env
    volumes:
      - ./appdata/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
    network_mode: "host"
    privileged: true
    restart: unless-stopped