services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:${BAZARR_VERSION}
    container_name: bazarr
    labels:
      - "co.elastic.logs/enabled=true"
    volumes:
      - ./appdata/bazarr/config:/config
      - ./data:/data
    ports:
      - ${BAZARR_PORT}:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped